server:
  port: 8083

application:
  title: ApiGateway
  version: 3.0

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
        - id: asesoria
          uri: lb://ASESORIA
          predicates:
            - Path=/api/v1/asesoria/**
        - id: alumno
          uri: lb://ASESORIA
          predicates:
            - Path=/api/v1/alumno/**
        - id: psicologo
          uri: lb://ASESORIA
          predicates:
            - Path=/api/v1/psicologo/**
        - id: reunionvirtual
          uri: lb://REUNIONVIRTUAL
          predicates:
            - Path=/api/v1/reunionvirtual/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true